### PR TITLE
Various

### PR DESCRIPTION
**Pull request by drdozer**
Added namespace support for elements.

Put in a placeholder for SVG.

Allowed Raw() to have mutable content.

### CODE REVIEW

**Comment by tindzk** [comment]
Looks great, thanks! Do you think it is worth it setting the namespace on every single element in the DOM?

**Comment by drdozer** [comment]
@tindzk it can't hurt - it's what scalatags does and that appears to generate dom objects that work. It also avoids us needing to expose two distinct DOM creation calls.

**Comment by drdozer** [comment]
Apologies for mixing two things in the one commit -- my git foo is weak and I don't know how to separate out the Raw() modification into its own commit.

**Comment by tindzk** [comment]
That sounds reasonable. Thanks!

**Pull request merged**
